Update tf-deploy.yml

diff --git a/.github/workflows/tf-deploy.yml b/.github/workflows/tf-deploy.yml
--- a/.github/workflows/tf-deploy.yml
+++ b/.github/workflows/tf-deploy.yml
@@ -24,6 +24,14 @@ on:
         options:
           - 'true'
           - 'false'
+      proceed_destroy:
+        description: 'Would you like to destroy the Terraform resources? (This will only create a plan, not execute it)'
+        required: true
+        default: 'false'
+        type: choice
+        options:
+          - 'true'
+          - 'false'
 
 jobs:
   init-and-plan:
@@ -157,3 +165,48 @@ jobs:
           ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
           ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
           ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
+
+  destroy:
+    runs-on: ubuntu-latest
+    needs: init-and-plan
+    if: github.event.inputs.proceed_destroy == 'true'
+
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
+        with:
+          terraform_version: '1.4.0'
+
+      - name: Reinitialize Terraform (Destroy)
+        run: |
+          echo "## Reinitializing Terraform for Destroy"
+          ENV_PATH="./environments"
+          cd "$ENV_PATH" || exit 1
+          terraform init -upgrade || { echo "Terraform init failed"; exit 1; }
+        env:
+          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
+          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
+          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
+          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
+
+      - name: Plan Terraform Destroy
+        run: |
+          echo "## Planning Terraform Destroy"
+          ENV_PATH="./environments"
+          cd "$ENV_PATH" || exit 1
+          terraform plan -destroy -var-file=terraform.tfvars -out=tfplan_destroy || { echo "Terraform destroy plan failed"; exit 1; }
+          echo "## Terraform Destroy Plan Completed"
+        env:
+          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
+          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
+          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
+          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
+
+      - name: Upload Terraform Destroy Plan as Artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: terraform-destroy-plan
+          path: ./environments/tfplan_destroy
